<?php


//////////////////////////////////////////////////////////////////////////////////////////////////PAGE
function main_introduction() {
	?>
	<form method='post' action='options.php' class="flatty-form">

	<div class="wrap flatty-form">
		<img src="<?php echo plugin_dir_url( __FILE__ ) . 'assets/flatty-logo.png' ?>" class="flatty-logo"/>
		<h1 style="padding:0; text-align:center; margin-bottom:2rem">Admin Options</h1>

			<div class="postbox flatty">
				<h2><i class="fa fa-paint-brush"></i> Theme style options</h2>
				
				<div class="option">
					<label for="flatty_light_style">Choose the light side</label>
					<input
						type="checkbox"
						name="flatty_light_style"
						id="flatty_light_style"
						value='1'
						<?php checked(1, get_option('flatty_light_style')); ?>
					/>
				</div>
				<div class="option">
					<label for="flatty_hide_sidebar_separator">Hide sidebar white separator</label>
					<input
						type="checkbox"
						name="flatty_hide_sidebar_separator"
						id="flatty_hide_sidebar_separator"
						value='1'
						<?php checked(1, get_option('flatty_hide_sidebar_separator')); ?>
					/>
				</div>
				<div class="option">
					<label for="flatty_post_style">Disable Flatty's "new post" styling</label>
					<input
						type="checkbox"
						name="flatty_post_style"
						id="flatty_post_style"
						value='1'
						<?php checked(1, get_option('flatty_post_style')); ?>
					/>
				</div>
				<div class="option">
					<label for="flatty_sidebar_minimal">Enable Flatty's "minimal sidebar" styling</label>
					<input
						type="checkbox"
						name="flatty_sidebar_minimal"
						id="flatty_sidebar_minimal"
						value='1'
						<?php checked(1, get_option('flatty_sidebar_minimal')); ?>
					/>
				</div>
			</div>


			<div id="branding-box" class="postbox flatty">
				<h2><i class="fa fa-scissors"></i> Whitelabel Wordpress</h2>
				<div class="option">
					<label for="flatty_wordpress_remove_generator">Remove Wordpress Meta tags</label>
					<div class="flatty-description">Like 'generated by Wordpress' and Wordpress version</div>
					<input
						type="checkbox"
						name="flatty_wordpress_remove_generator"
						id="flatty_wordpress_remove_generator"
						value='1'
						<?php checked(1, get_option('flatty_wordpress_remove_generator')); ?>
					/>
				</div>

				<div class="option">
					<label for="flatty_wp_hide_footer">Hide Wordpress Top Bar</label>
					<input
						type="checkbox"
						name="flatty_wp_hide_topbar"
						id="flatty_wp_hide_topbar"
						value='1'
						<?php checked(1, get_option('flatty_wp_hide_topbar')); ?>
					/>
				</div>

				<div class="option">
					<label for="flatty_wp_hide_footer">Hide Wordpress Logo</label>
					<input
						type="checkbox"
						name="flatty_wp_hide_topbar_logo"
						id="flatty_wp_hide_topbar_logo"
						value='1'
						<?php checked(1, get_option('flatty_wp_hide_topbar_logo')); ?>
					/>
				</div>

				<div class="option">
					<label for="flatty_wp_hide_footer">Hide Wordpress footer</label>
					<input
						type="checkbox"
						name="flatty_wp_hide_footer"
						id="flatty_wp_hide_footer"
						value='1'
						<?php checked(1, get_option('flatty_wp_hide_footer')); ?>
					/>
				</div>
			</div>

		</form>
	</div>
	<?php
}

?>
